# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='autor_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
